import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    // UNCOMMENT THIS TO TEST:
  // throw new Error("Triggering global error boundary"); 
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
